#!/usr/bin/env python3
"""IBM VGA 9x16 ROM font (int10h.org Oldschool PC Font Pack, Bm437_IBM_VGA_9x16.otb)
-> vgafont.h: 256 CP437 glyphs, 16 rows of 9 bits (bit 8 = leftmost pixel)."""
import os
from PIL import ImageFont, Image, ImageDraw
HERE = os.path.dirname(os.path.abspath(__file__))
font = ImageFont.truetype(os.path.join(HERE, 'Bm437_IBM_VGA_9x16.otb'), 16)
low = ('\u0000☺☻♥♦♣♠•◘○◙♂♀♪♫☼'
       '►◄↕‼¶§▬↨↑↓→←∟↔▲▼')
chars = [low[i] if i < 32 else ('⌂' if i == 127 else bytes([i]).decode('cp437')) for i in range(256)]
out = ['/* generated by mkfont.py from the IBM VGA 9x16 ROM font (int10h.org, CC BY-SA 4.0) */',
       'static const unsigned short vgafont[256][16] = {']
for i, ch in enumerate(chars):
    im = Image.new('1', (9, 16), 0)
    if i:
        ImageDraw.Draw(im).text((0, 0), ch, font=font, fill=1)
    rows = [sum(1 << (8 - x) for x in range(9) if im.getpixel((x, y))) for y in range(16)]
    out.append('\t{' + ','.join('0x%03x' % r for r in rows) + '},')
out.append('};')
open(os.path.join(HERE, 'vgafont.h'), 'w').write('\n'.join(out) + '\n')
