#!/usr/bin/env python3
"""ClassicRogue sprites (tiles by Oryx, 16x24, 1 bit; classicrogue/sprites.png
from classicrogue/extract.py) -> tiles.h for Rogue PC (RVIP step 4).
The sprites have no colour: the frontends draw each one in the colour the
original text mode gives that cell (tile_col[] for terrain drawn under
things)."""
import os
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__))
im = Image.open(os.path.join(HERE, 'classicrogue', 'sprites.png')).convert('RGBA')
W, H, N = 16, 24, 92

# sprite numbers in the ClassicRogue sheet
MON = list(range(5, 31))                 # A..Z, Rogue PC's own monsters
WEAP = [44] + list(range(51, 60))        # mace, long sword .. spear (extern.c order)
ARM = list(range(60, 68))                # leather armor .. plate mail
TL = dict(PLAYER=31, VWALL=32, TWALL=33, LLWALL=34, BWALL=35, LRWALL=36,
          PASSAGE=37, FLOOR=39, DOOR=40, STAIRS=41, TRAP=42, AMULET=43,
          FOOD=45, POTION=46, RING=47, SCROLL=48, STAFF=49, WAND=50, GOLD=68)
# colours of the original text mode (src/curses.c cur_addch), for terrain under things
COL = {32: 6, 33: 6, 34: 6, 35: 6, 36: 6, 37: 7, 39: 10, 40: 6, 41: 2, 42: 5}

o = ['/* generated by mktiles.py from classicrogue/sprites.png (tiles by Oryx) */',
     '#define NTILES %d' % N, '#define TW %d' % W, '#define TH %d' % H,
     'static const unsigned short tile_bits[NTILES][TH] = {']
for t in range(N):
    rows = []
    for y in range(H):
        r = 0
        for x in range(W):
            if im.getpixel(((t % 23) * W + x, (t // 23) * H + y))[3]:
                r |= 1 << (15 - x)
        rows.append('0x%04x' % r)
    o.append('{' + ','.join(rows) + '},')
o.append('};')
o.append('static const unsigned char tile_col[NTILES] = {%s};' % ','.join(str(COL.get(t, 7)) for t in range(N)))
o.append('static const short t_mon[26] = {%s};' % ','.join(map(str, MON)))
o.append('static const short t_weap[10] = {%s};' % ','.join(map(str, WEAP)))
o.append('static const short t_arm[8] = {%s};' % ','.join(map(str, ARM)))
for k, v in TL.items():
    o.append('#define TL_%s %d' % (k, v))
open(os.path.join(HERE, 'tiles.h'), 'w').write('\n'.join(o) + '\n')
print(N, 'tiles')
